Update for PostgreSQL v12.3 and docker release script
RHEAGROUP/CDP4-Docker pull request #5
Opened 2020-06-08 16:22 UTC by alexatrhea

The version of the DB updated to 12.3 giving significant performance boost.

Also included a release batchscript. Usage in the readme.

2020-06-08 16:36 UTC, samatstariongroup requested changes

2020-06-08 16:36 UTC, samatrhea commented on README.md
> +The `CDP4 Database Bare - Community Edition` image is based on the official PostgreSQL 9.6.14 image. It does not contain the CDP4 SQL Schema, only the minimal setup that is required to execute the [E
should this still state version 9.6.14?

2020-06-08 16:40 UTC, alexatrhea commented on README.md
> +The `CDP4 Database Bare - Community Edition` image is based on the official PostgreSQL 9.6.14 image. It does not contain the CDP4 SQL Schema, only the minimal setup that is required to execute the [E
missed it, corrected

2020-06-08 17:28 UTC, samatstariongroup approved these changes

2020-06-08 21:11 UTC, nathanatstariongroup approved these changes

2020-06-09 07:42 UTC, lxatstariongroup approved these changes

2020-06-09 07:44 UTC, merged